name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install alsa and udev
      run: sudo apt-get update -yq; sudo apt-get install -yq --no-install-recommends libasound2-dev libudev-dev

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2.6.0

    - name: fmt
      run: cargo fmt --all -- --check

    - name: check
      run: cargo check

    - name: clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
